### ISSUE TITLE
Masternode fails to handle serialized or unserialized request, error not handled

### ISSUE THREAD

**Issue by v6** [Lamden/cilantro#13]
Version: 0e3616cbc25f75b3d99f89be3c8d27eca0d76ea6

When you have a minute, I'm mystified as to what caused the following error in the lamden masternode: 

##Output

```
'Request' object has no attribute 'decode'

Error handling request

Traceback (most recent call last):

  File "/home/nb/Envs/lamdencilantro/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 410, in start

    resp = yield from self._request_handler(request)

  File "/home/nb/Envs/lamdencilantro/lib/python3.6/site-packages/aiohttp/web.py", line 332, in _handle

    for app in match_info.apps

AssertionError: Handler <function Masternode.process_tranasaction at 0x7f3e006ad378> should return response instance, got <class 'dict'> [middlewares [(<function _fix_request_current_app.<locals>.impl at 0x7f3e0136cd08>, True)]]

'Request' object has no attribute 'decode'

Error handling request

Traceback (most recent call last):

  File "/home/nb/Envs/lamdencilantro/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 410, in start

    resp = yield from self._request_handler(request)

  File "/home/nb/Envs/lamdencilantro/lib/python3.6/site-packages/aiohttp/web.py", line 332, in _handle

    for app in match_info.apps

AssertionError: Handler <function Masternode.process_tranasaction at 0x7f3e006ad378> should return response instance, got <class 'dict'> [middlewares [(<function _fix_request_current_app.<locals>.impl at 0x7f3e0136cd08>, True)]]



```

Full output from the `masternode` server side: 

https://0bin.net/paste/-rwcDOMFQknumERW#cumuNsBFf6Inv6hVvIq4VXjL2YylUUM2vGUGIAlAosf

Full output from the `requests` HTTP client side: 

https://0bin.net/paste/-wbHxyb51e7TtFFR#ystHH52LECIq50z-PmFKTz4VYdoZTkl9E2f65wJkd83

##Assessment

If this is something for which I need to dig into the aiohttp docs let me know. 

1. It looks like the server's set up to handle requests at http://localhost:8080/

2. The request is correctly formatted (I've sent both serialized and unserialized JSON)

3. The Masternode doesn't seem to be handling the error at all

**Comment by v6** [comment]
I didn't set up the router correctly

I used `app.router.add_post('/', nathanNodeNotBroken.process_transaction)`

In stead of `app.router.add_post('/', nathanNodeNotBroken.process_request)`

No wonder the master node complained about being unable to do JSON decoding on a request!

Anyway, it seems to work now just fine:
Server: 
![image](https://user-images.githubusercontent.com/5750764/35715174-c8c673ae-0785-11e8-8eec-2c154f60631c.png)

HTTP Client: 
![image](https://user-images.githubusercontent.com/5750764/35715194-dd3febd0-0785-11e8-80b3-b3076b97e825.png)
